### ISSUE TITLE
Scripted test failure

### ISSUE THREAD

**Issue by chbatey** [akka/akka-grpc-quickstart-java.g8#47]
```
Running akka-grpc-java-seed / scripted
[error] [info] [launcher] getting org.scala-sbt sbt 1.4.4  (this may take some time)...
[error] :: loading settings :: url = jar:file:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.12/sbt-launch-1.3.12.jar!/org/apache/ivy/core/settings/ivysettings.xml
[error] :: loading settings :: url = jar:file:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.3.12/sbt-launch-1.3.12.jar!/org/apache/ivy/core/settings/ivysettings.xml
[error] :: retrieving :: org.scala-sbt#boot-app
[error] 	confs: [default]
[error] 	84 artifacts copied, 0 already retrieved
[error] [info] [launcher] getting Scala 2.12.12 (for sbt)...
[error] :: retrieving :: org.scala-sbt#boot-scala
[error] 	confs: [default]
[error] 	6 artifacts copied, 0 already retrieved
[error] [error] [launcher] could not retrieve Scala 2.12.12: missing scala.tools.nsc.Global
[error] x akka-grpc-java-seed / scripted 
[error]  Cause of test exception: {line 1}  Command failed: Remote sbt initialization failed
[error] java.lang.RuntimeException: Failed tests:
[error] 	akka-grpc-java-seed / scripted
[error] 
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.scriptedtest.ScriptedRunner.reportErrors(ScriptedTests.scala:565)
[error] 	at sbt.scriptedtest.ScriptedRunner.runAll(ScriptedTests.scala:568)
[error] 	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:513)
[error] 	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:477)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(De
```

https://travis-ci.com/github/akka/akka-grpc-quickstart-java.g8/jobs/449978112

**Comment by raboof** [comment]
This works locally but not (even after rebuilding) on travis.

I'd like to clear the travis cache but can't due to https://travis-ci.community/t/cant-clear-caches-as-caches-settings-page-empty/10058 . Opened a travis-ci support ticket about it.

**Comment by raboof** [comment]
#48
